import type { Metadata } from "next";
import { SpeedInsights } from "@vercel/speed-insights/next"
// auth
import { getServerSession } from "next-auth";
import SessionProvider from "./_components/SessionProvider/SessionProvider";
// font
import { Roboto, Roboto_Mono } from "next/font/google";
// styles
import "./globals.scss";

const roboto = Roboto_Mono({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Welcome",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={roboto.className}>
        <SessionProvider session={session}>{children}
           <SpeedInsights/>
        </SessionProvider>
      </body>
    </html>
  );
}
